---
- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install Nginx
  become: yes
  apt: pkg=nginx state=latest

- name: Change default nginx site
  become: yes
  template: src=default dest=/etc/nginx/sites-available/default
  notify: restart nginx
